web/router.ex
defmodule Nemo.Router do
  use Nemo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Nemo do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",    SessionController, :new
    post   "/login",    SessionController, :create
    delete "/logout",   SessionController, :delete
    get    "/words",    WordsController,   :index
    get    "/account",  AccountController, :index

  end

   scope "/api", Nemo.Api do
     pipe_through :api
     get "/stats", TranslationController, :index
   end
end

web/views/layout_view.ex
defmodule Nemo.LayoutView do
  use Nemo.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Nemo</title>
    <link rel="shortcut icon" type="image/png" href="/assets/favicon.png"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="<%= static_path(@conn, "/js/utils.js") %>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <div class="container">

      <header class="header">
        <nav role="navigation">

          <ul class="nav nav-pills navbar-left">
            <li>
              <%= link "Nemo", to: page_path(@conn, :index) %>
            </li>
          </ul>

          <ul class="nav nav-pills navbar-right">

            <%= if logged_in?(@conn) do %>

              <li><%= link current_user(@conn).username, to: account_path(@conn, :index), method: :get %></li>
              <li><%= link "Words", to: words_path(@conn, :index), method: :get %></li>
              <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>

            <% else %>

              <li>
                <%= link "Login", to: session_path(@conn, :new) %>
              </li>
              <li>
                <%= link "Register", to: registration_path(@conn, :new) %>
              </li>

            <% end %>

          </ul>
        </nav>
      </header>

      <!-- <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p> -->

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>